apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dbbat.fullname" . }}
  labels:
    {{- include "dbbat.labels" . | nindent 4 }}
data:
  DBB_LISTEN_PG: {{ .Values.config.listenPg | quote }}
  DBB_LISTEN_API: {{ .Values.config.listenApi | quote }}
  DBB_BASE_URL: {{ .Values.config.baseUrl | quote }}
  {{- if .Values.config.runMode }}
  DBB_RUN_MODE: {{ .Values.config.runMode | quote }}
  {{- end }}
  {{- if .Values.config.keyFile }}
  DBB_KEYFILE: {{ .Values.config.keyFile | quote }}
  {{- end }}
