{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dbbat.fullname" . }}
  labels:
    {{- include "dbbat.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.encryptionKey }}
  DBB_KEY: {{ .Values.secrets.encryptionKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.databasePassword }}
  DB_PASSWORD: {{ .Values.secrets.databasePassword | b64enc | quote }}
  {{- end }}
  {{- if or .Values.postgresql.external.dsn (and .Values.postgresql.external.host .Values.postgresql.external.username) }}
  DBB_DSN: {{ include "dbbat.dsn" . | b64enc | quote }}
  {{- end }}
{{- end }}
