apiVersion: v1
kind: Service
metadata:
  name: {{ include "dbbat.fullname" . }}
  labels:
    {{- include "dbbat.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.service.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dbbat.selectorLabels" . | nindent 4 }}
